apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-vkew
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-vkew
    app.kubernetes.io/part-of: component-annotation-dotnet-component
  name: devfile-sample-dotnet60-bhwla
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-dotnet60-basic-vkew
    weight: null
status: {}
